/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayInterrogatorRouteImport } from './routes/play/interrogator'
import { Route as PlayLabRouteImport } from './routes/play/lab'
import { Route as PlaySubjectRouteImport } from './routes/play/subject'
import { Route as TrialIdRouteImport } from './routes/trial.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayInterrogatorRoute = PlayInterrogatorRouteImport.update({
  id: '/play/interrogator',
  path: '/play/interrogator',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLabRoute = PlayLabRouteImport.update({
  id: '/play/lab',
  path: '/play/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySubjectRoute = PlaySubjectRouteImport.update({
  id: '/play/subject',
  path: '/play/subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialIdRoute = TrialIdRouteImport.update({
  id: '/trial/$id',
  path: '/trial/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/login': typeof LoginRoute
  '/play/interrogator': typeof PlayInterrogatorRoute
  '/play/lab': typeof PlayLabRoute
  '/play/subject': typeof PlaySubjectRoute
  '/trial/$id': typeof TrialIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/login': typeof LoginRoute
  '/play/interrogator': typeof PlayInterrogatorRoute
  '/play/lab': typeof PlayLabRoute
  '/play/subject': typeof PlaySubjectRoute
  '/trial/$id': typeof TrialIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/login': typeof LoginRoute
  '/play/interrogator': typeof PlayInterrogatorRoute
  '/play/lab': typeof PlayLabRoute
  '/play/subject': typeof PlaySubjectRoute
  '/trial/$id': typeof TrialIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/login'
    | '/play/interrogator'
    | '/play/lab'
    | '/play/subject'
    | '/trial/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/login'
    | '/play/interrogator'
    | '/play/lab'
    | '/play/subject'
    | '/trial/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/login'
    | '/play/interrogator'
    | '/play/lab'
    | '/play/subject'
    | '/trial/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  LoginRoute: typeof LoginRoute
  PlayInterrogatorRoute: typeof PlayInterrogatorRoute
  PlayLabRoute: typeof PlayLabRoute
  PlaySubjectRoute: typeof PlaySubjectRoute
  TrialIdRoute: typeof TrialIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/interrogator': {
      id: '/play/interrogator'
      path: '/play/interrogator'
      fullPath: '/play/interrogator'
      preLoaderRoute: typeof PlayInterrogatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/lab': {
      id: '/play/lab'
      path: '/play/lab'
      fullPath: '/play/lab'
      preLoaderRoute: typeof PlayLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/subject': {
      id: '/play/subject'
      path: '/play/subject'
      fullPath: '/play/subject'
      preLoaderRoute: typeof PlaySubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial/$id': {
      id: '/trial/$id'
      path: '/trial/$id'
      fullPath: '/trial/$id'
      preLoaderRoute: typeof TrialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  LoginRoute: LoginRoute,
  PlayInterrogatorRoute: PlayInterrogatorRoute,
  PlayLabRoute: PlayLabRoute,
  PlaySubjectRoute: PlaySubjectRoute,
  TrialIdRoute: TrialIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
